// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneWeb.Data;

namespace PhoneWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "a3ca0bdb-7765-4475-b53b-7637ca962ba7",
                            ConcurrencyStamp = "60c63dea-418f-4922-9847-893655f2d2ac",
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        },
                        new
                        {
                            Id = "98fe209c-b90e-4531-a1b8-513dee3c3c6d",
                            ConcurrencyStamp = "b16c84e5-f1c6-4805-bcf6-2ea092174553",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PhoneWeb.Models.Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Áo Thun Ngắn Tay"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Áo Thun Dài Tay"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Áo Thun Cổ"
                        });
                });

            modelBuilder.Entity("PhoneWeb.Models.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PhoneWeb.Models.Domain.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PhoneWeb.Models.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 701, DateTimeKind.Local).AddTicks(8700),
                            Descriptions = "Chất liệu: Cotton 2 chiều, Thành phần: 100% Cotton,  Co dãn 2 chiều, Thấm hút mồ hôi tốt mang lại cảm giác thoáng mái, Họa tiết: ép Foil ",
                            ProductImage = "1.jpg",
                            ProductName = "Áo Thun TN R Thiết Kế BD-A93",
                            ProductPrice = 300000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3198),
                            Descriptions = "Chất liệu: Cotton 2 chiều, Thành phần: 100% Cotton, Co dãn 2 chiều, Thấm hút mồ hôi tốt mang lại cảm giác thoáng mát ",
                            ProductImage = "2.jpg",
                            ProductName = "Áo Thun TN TC Đơn Giản BN01",
                            ProductPrice = 300000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3272),
                            Descriptions = "Chất liệu: Cotton 4 Chiều, Thành phần: 95% cotton 5% Spandex, Co giãn tốt, Độ bền cao ",
                            ProductImage = "3.jpg",
                            ProductName = "Áo Thun Cổ Trụ TC Đơn Giản J01",
                            ProductPrice = 300000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3276),
                            Descriptions = "Chất liệu: Cotton 2 chiều, Thành phần: 100% Cotton, Co dãn 2 chiều, Thấm hút mồ hôi tốt mang lại cảm giác thoáng mái, Họa tiết: in trame, in dẻo ",
                            ProductImage = "4.jpg",
                            ProductName = "Áo Thun TN R Thiết Kế BO01",
                            ProductPrice = 300000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3281),
                            Descriptions = "Chất liệu: Cotton 2 chiều, Thành phần: 100% Cotton, Co dãn 2 chiều, Thấm hút mồ hôi tốt mang lại cảm giác thoáng mái, Họa tiết: in trame ",
                            ProductImage = "5.jpg",
                            ProductName = "Áo Thun TN R Thiết Kế BD-A90",
                            ProductPrice = 300000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3283),
                            Descriptions = "Chất liệu: Cotton 2 chiều, Thành phần: 100% Cotton, Co dãn 2 chiều, Thấm hút mồ hôi tốt mang lại cảm giác thoáng mát ",
                            ProductImage = "6.jpg",
                            ProductName = "Áo Thun TN TC Thiết Kế B1CF06",
                            ProductPrice = 250000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3286),
                            Descriptions = "Chất liệu: Cotton 2 chiều, Thành phần: 100% Cotton,  Co dãn 2 chiều, Thấm hút mồ hôi tốt mang lại cảm giác thoáng mái, Họa tiết: ép Foil ",
                            ProductImage = "7.jpg",
                            ProductName = "Áo Thun TD R Thiết Kế A02",
                            ProductPrice = 250000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3288),
                            Descriptions = "Chất liệu: Cotton 2 chiều, Thành phần: 100% Cotton, Co dãn 2 chiều, Thấm hút mồ hôi tốt mang lại cảm giác thoáng mát ",
                            ProductImage = "8.jpg",
                            ProductName = "Áo Thun TD R Thiết Kế B02",
                            ProductPrice = 250000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3290),
                            Descriptions = "COUPLE TAY DÀI, Diện áo thun couple đã trở thành xu hướng của giới trẻ hiện đại, Đặc biệt áo thun tay dài raplan, màu sắc tươi mới, Thiết kế Unisex, dễ dàng mix với nhiều trang phục khác nhau, Chất liệu cotton 2 chiều, thoáng mát, bề mặt mịn đẹp ",
                            ProductImage = "9.jpg",
                            ProductName = "Áo Thun TD TC Đơn Giản B4AA01",
                            ProductPrice = 250000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3293),
                            Descriptions = "COUPLE TAY DÀI, Diện áo thun couple đã trở thành xu hướng của giới trẻ hiện đại, Đặc biệt áo thun tay dài raplan, màu sắc tươi mới, Thiết kế Unisex, dễ dàng mix với nhiều trang phục khác nhau, Chất liệu cotton 2 chiều, thoáng mát, bề mặt mịn đẹp ",
                            ProductImage = "10.jpg",
                            ProductName = "Samsung Galaxy A71",
                            ProductPrice = 250000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3297),
                            Descriptions = "COUPLE TAY DÀI, Diện áo thun couple đã trở thành xu hướng của giới trẻ hiện đại, Đặc biệt áo thun tay dài raplan, màu sắc tươi mới, Thiết kế Unisex, dễ dàng mix với nhiều trang phục khác nhau, Chất liệu cotton 2 chiều, thoáng mát, bề mặt mịn đẹp ",
                            ProductImage = "11.jpg",
                            ProductName = "Áo Thun Cổ Trụ TC Đơn Giản B2R01",
                            ProductPrice = 250000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3300),
                            Descriptions = "COUPLE TAY DÀI, Diện áo thun couple đã trở thành xu hướng của giới trẻ hiện đại, Đặc biệt áo thun tay dài raplan, màu sắc tươi mới, Thiết kế Unisex, dễ dàng mix với nhiều trang phục khác nhau, Chất liệu cotton 2 chiều, thoáng mát, bề mặt mịn đẹp ",
                            ProductImage = "12.jpg",
                            ProductName = "Áo Thun Cổ Trụ TC Thiết Kế B2R04",
                            ProductPrice = 250000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3302),
                            Descriptions = "COUPLE TAY DÀI, Diện áo thun couple đã trở thành xu hướng của giới trẻ hiện đại, Đặc biệt áo thun tay dài raplan, màu sắc tươi mới, Thiết kế Unisex, dễ dàng mix với nhiều trang phục khác nhau, Chất liệu cotton 2 chiều, thoáng mát, bề mặt mịn đẹp ",
                            ProductImage = "13.jpg",
                            ProductName = "Áo Thun Cổ Trụ TC Thiết Kế B04",
                            ProductPrice = 250000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 3,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3304),
                            Descriptions = "COUPLE TAY DÀI, Diện áo thun couple đã trở thành xu hướng của giới trẻ hiện đại, Đặc biệt áo thun tay dài raplan, màu sắc tươi mới, Thiết kế Unisex, dễ dàng mix với nhiều trang phục khác nhau, Chất liệu cotton 2 chiều, thoáng mát, bề mặt mịn đẹp ",
                            ProductImage = "14.jpg",
                            ProductName = "Áo Thun Cổ Trụ TC Thiết Kế B1Q02",
                            ProductPrice = 250000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 3,
                            CreateDate = new DateTime(2020, 11, 23, 13, 12, 31, 703, DateTimeKind.Local).AddTicks(3307),
                            Descriptions = "COUPLE TAY DÀI, Diện áo thun couple đã trở thành xu hướng của giới trẻ hiện đại, Đặc biệt áo thun tay dài raplan, màu sắc tươi mới, Thiết kế Unisex, dễ dàng mix với nhiều trang phục khác nhau, Chất liệu cotton 2 chiều, thoáng mát, bề mặt mịn đẹp ",
                            ProductImage = "15.jpg",
                            ProductName = "Áo Thun Cổ Trụ TC Thiết Kế F01",
                            ProductPrice = 250000.0,
                            ProductQuantity = 100
                        });
                });

            modelBuilder.Entity("PhoneWeb.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PhoneWeb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PhoneWeb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneWeb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PhoneWeb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoneWeb.Models.Domain.OrderDetail", b =>
                {
                    b.HasOne("PhoneWeb.Models.Domain.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneWeb.Models.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoneWeb.Models.Domain.Product", b =>
                {
                    b.HasOne("PhoneWeb.Models.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
